language: python
python:
- 3.6
services:
- mysql
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install -e .
- pip install -r requirements.txt
- pip install coveralls
- pip install flake8
before_script:
- flake8 ambition_dashboard
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=ambition_dashboard manage.py test
after_success:
- coveralls
notifications:
  slack:
    secure: iXjo67CbggxWdVhntIAOogMSpRMBfvJnH9+KVdV+vXC4WCV7b3UL6J9KHNSdADGdnYXb56FiKYSP+lKQqD6fVEAzHT0iaNpqeMYYk9HfNhGWMax5hShA9O6aN1K404qstHpR5qDw62MulXndRtSLWjSah68m+F0CvAXvDF70HJ9NGllE+qotQnUJjRejEvZNMbszbJyIgF/lgP681uKKq/RUUHd/C7tmyiQEcsxUqT1Mq6vCTv5151NnEE1YIX7yk4zkUbkic6+BqIs0LidODOZvQlnZrIe+jl0ryva9myEweBB/Hk+je/DglbOdY6mkHp2IdSlUp4TyC5mSrheAFWNUgQaU9cZskKQgm8nlHzLy/BLrYnDkLH6YsW/DrYDyA6j/PBDB2E3Memjf1xiEYb50/XU0NzDq6nTuMD3cKPa3Yc0zjrDOjH/qXv5gIWz4nzALODsXcszlbgvwCcdB2mgn22d1BBmo/Eqj35jJUT2T9lrOtze7V0F/fnVxyg9S78P/Pu1IXw20liKDTSFCDgqW+uXIJ9mXtuLfu8cQUCtAF4DsaFojgQNuf2Q2uhHGzjo8ZHnSFPqqTexzmEjY0J8MqdkxNVPwlctbbF3e37ijCBYJ6fpfhY0BfifhkEEJx3zzjUUJsS+y8olYprovmUe59UcNjftYRrBKC/TvPL8=
